// Reads content/survey-questions.json and writes
// api/internal/questions/questions_gen.go.
//
// Run via `npm run gen:go`. The generated file is checked in;
// CI fails if it drifts from the JSON source.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type RawQuestion = {
  id: string
  type: string
  label: string
  choices?: string[]
  min?: number
  max?: number
  maxLength?: number
}

const KNOWN_TYPES = new Set([
  'short_text',
  'long_text',
  'number',
  'scale_1_10',
  'single_choice',
  'multi_choice',
])

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const jsonPath = join(repoRoot, 'content', 'survey-questions.json')
const outPath = join(repoRoot, 'api', 'internal', 'questions', 'questions_gen.go')

const raw = readFileSync(jsonPath, 'utf8')
const questions: RawQuestion[] = JSON.parse(raw)

const seen = new Set<string>()
for (const q of questions) {
  if (!KNOWN_TYPES.has(q.type)) {
    throw new Error(`unknown question type "${q.type}" on id "${q.id}"`)
  }
  if (!/^[a-z][a-z0-9_]*$/.test(q.id)) {
    throw new Error(`question id "${q.id}" is not a valid snake_case identifier`)
  }
  if (seen.has(q.id)) {
    throw new Error(`duplicate question id "${q.id}"`)
  }
  seen.add(q.id)
}

const lit = (s: string) => JSON.stringify(s)

function emitQuestion(q: RawQuestion): string {
  const fields: string[] = []
  fields.push(`Id: ${lit(q.id)}`)
  fields.push(`Type: ${lit(q.type)}`)
  fields.push(`Label: ${lit(q.label)}`)
  if (q.choices && q.choices.length > 0) {
    fields.push(`Choices: []string{${q.choices.map(lit).join(', ')}}`)
  }
  if (q.min !== undefined) fields.push(`Min: intPtr(${q.min})`)
  if (q.max !== undefined) fields.push(`Max: intPtr(${q.max})`)
  if (q.maxLength !== undefined) fields.push(`MaxLength: intPtr(${q.maxLength})`)
  return `\t{${fields.join(', ')}},`
}

const body = `// Code generated by scripts/gen-questions-go.ts. DO NOT EDIT.

package questions

// Question is the canonical typed copy of the survey question schema.
// The source of truth is content/survey-questions.ts (with its JSON sidecar).
type Question struct {
\tId        string   \`json:"id"\`
\tType      string   \`json:"type"\`
\tLabel     string   \`json:"label"\`
\tChoices   []string \`json:"choices,omitempty"\`
\tMin       *int     \`json:"min,omitempty"\`
\tMax       *int     \`json:"max,omitempty"\`
\tMaxLength *int     \`json:"maxLength,omitempty"\`
}

func intPtr(i int) *int { return &i }

var Questions = []Question{
${questions.map(emitQuestion).join('\n')}
}

var QuestionsByID = func() map[string]Question {
\tm := make(map[string]Question, len(Questions))
\tfor _, q := range Questions {
\t\tm[q.Id] = q
\t}
\treturn m
}()
`

writeFileSync(outPath, body)
console.log(`wrote ${outPath} (${questions.length} questions)`)
